basePath: /
host: localhost:8000
info:
  contact:
    name: Wesly Ramalho
  description: Product API
  termsOfService: http://swagger.io/terms
  title: Primeira API em Go
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
